export GCLOUD_PROJECT_ID=<YOUR_GCLOUD_PROJECT_ID>
export IMAGE_TAG=<YOUR_DOCKER_IMAGE_TAG>
export PROJECT_NAME=<YOUR_CLOUD_RUN_PROJECT_NAME>

docker build -t $IMAGE_TAG .

docker tag $IMAGE_TAG gcr.io/$GCLOUD_PROJECT_ID/$PROJECT_NAME
docker push gcr.io/$GCLOUD_PROJECT_ID/$PROJECT_NAME

gcloud run deploy --image gcr.io/$GCLOUD_PROJECT_ID/$PROJECT_NAME --platform managed